#!/usr/bin/env python3
"""Write approved Alibaba listings into Alibaba's bulk-upload spreadsheet: export/alibaba-bulk-upload.xlsx.

  alibaba_xlsx.py --dir D [--only ID ...]

Used when the store is not connected to Xelent API for direct submission. The layout copies Alibaba's
"Default template (recommended)" (post.alibaba.com/product/migration/excel.htm): row 1 empty, row 2 section labels,
row 3 the 57 column headers the parser binds to, row 4 the template's instructions, data from row 5, and a
unitSheet tab. Images must be public https links, so run `node publish.mjs --dir D --upload-only` first: it hosts the
exported JPEGs on Xelent API and records their links in published.json. Unused links expire after 30 days, so
upload the spreadsheet in Alibaba's seller centre (Products > Bulk upload) within that time.
"""
import argparse, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import load  # noqa: E402

try:
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font
except ImportError:
    sys.exit("openpyxl is needed: python3 -m pip install openpyxl")

SECTION = {1: "Basic Information of Your Listings on Alibaba.com", 11: "Category details", 22: "Selling type",
           28: "SKU Pricing \n(Fill out this section ONLY if you have selected corresponding selling method in column Z) ",
           39: "Tiered pricing\n(Fill out this section ONLY if you have selected corresponding selling method in column Z) ",
           45: "Range pricing\n(Fill in this section ONLY if you have selected the corresponding selling method in column Z)",
           47: "Logistics information \n(Green * are mandatory fields for RTS products)"}
HEADERS = (["* Product title", "* Product image 1"] + [f"Product image {i}" for i in range(2, 7)] +
           ["Product description", "Place of origin", "Brand name", "Category"] +
           [x for i in range(1, 6) for x in (f"Product attribute name {i}", f"Product attribute value {i}")] +
           ["Sell product by", "Batch quantity", "Unit", "Currency", "Pricing type", "Inventory", "SPU ID (Model number)", "SKU code", "SKU pricing"] +
           [x for i in range(1, 5) for x in (f"SKU attribute name {i}", f"SKU attribute value {i}")] +
           [x for i in range(1, 4) for x in (f"Tiered pricing {i}", f"MOQ {i}")] +
           ["Range pricing (Lower limit)", "Range pricing (Higher limit)", "* Gross weight (KG)", "* Shipping template name",
            "* Shipping quantity 1", "* Estimated shipping lead time 1", "Shipping quantity 2", "Estimated shipping lead time 2",
            "Shipping quantity 3", "Estimated shipping lead time 3", "Product size-Length", "Product size-Width", "Product size-Height"])
B4 = "Same rule as cell B4"
INSTRUCTIONS = (
    ["1. Do not enter any unsupported symbols such as !\n2. This field is limited to 128 characters",
     "1. One cell for one image URL.\n2. It contains https:// \n3. The URL must be valid. You can view the picture online just by clicking this link.",
     B4, B4, B4, B4, B4 + "\n\nMaximum of 6 images allowed.",
     "1. Product description will be shown on the product page.\n2. This field is limited to 20,000 characters in length.",
     "Fill them in if useful, otherwise leave blank", "Fill them in if useful, otherwise leave blank",
     "Fill in your preferred category.\nIf left blank, this field will be generated by Alibaba AI",
     "Attribute name for the product.\n* Category attribute will not affect the pricing & inventory.",
     "Attribute value for the product.\n* Category attribute will not affect the pricing & inventory."]
    + ["Same rule as cell L4", "Same rule as cell M4"] * 4
    + ["Select to sell by unit or batch",
       "Only fill in this column if \"Selling method\" is \"By batch\". Enter the number of units per batch (eg., if there are 12 pieces per batch, then the batch quantity is 12). \n\nYou can't write zero or negative numbers in this column.",
       "If left empty, the unit will be pieces by default. ", "Fill in the currency code (ISO 4217). E.g.: USD",
       "Tiered pricing: Please fill in columns K - P.\nSKU pricing: Please fill in columns V - AE.\nRange pricing: Please fill in columns AS - AT.",
       "Inventory of the product. Only non-zero integers are supported. If you leave it blank, we will set it to 9999999 by default.",
       "This is a mandatory field if you have more than one SKU. \nAll rows to be grouped into a single product listing must share the same SPU ID to ensure accurate grouping.",
       "SKU ID is not mandatory. \nBut if sellers choose to fill it out, all rows must have unique SKU IDs.\n",
       "Price of the product specific SKU.\nFill in the numbers only.\nDo not enter 0.",
       "Attribute name for this product. This attribute will affect the pricing & inventory E.g.: Color\n\nOne cell for one value.\n 40 characters max.",
       "Attribute value for this product. E.g.: Green\nOne cell for one value.\n 70 characters max."]
    + ["Same rule as cell AE4\nFill in if useful, otherwise leave blank", "Same rule as cell AF4\nFill in if useful, otherwise leave blank"] * 3
    + ["1st pricing tier\n\nTiered pricing 1 > Tiered pricing 2 > Tiered pricing 3\n\nFill in with numbers only.\nOne value for one cell.",
       "1st tier MOQ\n\nMOQ 1 < MOQ 2 < MOQ 3\n\nFill in with numbers only.\nOne value for one cell.",
       "2nd pricing tier\n\nTiered pricing 1 > Tiered pricing 2 > Tiered pricing 3.\n\nFill in with numbers only.\nOne value for one cell.",
       "2nd tier MOQ\n\nMOQ 1 <  MOQ 2 < MOQ 3\n\nFill in with numbers only.\nOne value for one cell.",
       "3rd pricing tier\n\nTiered pricing 1 > Tiered pricing 2 > Tiered pricing 3.\n\nFill in with numbers only.\nOne value for one cell.",
       "3rd tier MOQ\n\nMOQ 1 < MOQ 2 <  MOQ3\n\nFill in with numbers only.\nOne value for one cell.",
       "The lower limit price for range pricing.\n\nFill in with numbers only.\nOne value for one cell.",
       "The higher limit price for range pricing.\n\nFill in with numbers only.\nOne value for one cell.",
       "Mandatory field if you want to list RTS products.\n\nFill in with numbers only. \nDo not enter units.",
       "Mandatory field if you want to list RTS products. Check the template name here: https://i.alibaba.com/trade/logistics/shippingTemplates.htm",
       "Used for setting quantity-based lead time.\n\nShipping quantity 1 < Shipping quantity 2 < Shipping quantity 3",
       "The estimated lead time for shipping quantity \nFill in with numbers only. \nDo not enter units.\n\nEstimated shipping lead time 1 < Estimated shipping lead time 2 < Estimated shipping lead time 3",
       "Same rule for cell AW4\n\nShipping quantity 1 < Shipping quantity 2 < Shipping quantity 3",
       "Same rule for cell AX4\n\nEstimated shipping lead time 1 < Estimated shipping lead time 2 < Estimated shipping lead time 3",
       "Same rule for cell AW4\n\nShipping quantity 1 < Shipping quantity 2 < Shipping quantity 3",
       "Same rule for cell AX4\n\nEstimated shipping lead time 1 < Estimated shipping lead time 2 < Estimated shipping lead time 3"]
    + ["Optional field, unit: cm. If you need to upload dimensions, you need to fill in the length, width, and height."] * 3)
UNITS = ("Bag/Bags|Kilometer/Kilometers|Ton/Tons|Square Meter/Square Meters|Cubic Meter/Cubic Meters|Dozen/Dozens|Gallon/Gallons|"
         "Kilogram/Kilograms|Gram/Grams|Bushel/Bushels|Barrel/Barrels|Short Ton/Short Tons|Set/Sets|Pack/Packs|Liter/Liters|Yard/Yards|"
         "Milligram/Milligrams|Unit/Units|Acre/Acres|Ampere/Amperes|Box/Boxes|Carton/Cartons|Pound/Pounds|Case/Cases|Centimeter/Centimeters|"
         "Chain/Chains|Cubic Centimeter/Cubic Centimeters|Cubic Foot/Cubic Feet|Cubic Inch/Cubic Inches|Cubic Yard/Cubic Yards|Degrees Celsius|"
         "Degrees Fahrenheit|Dram/Drams|Piece/Pieces|Fluid Ounce/Fluid Ounces|Foot/Feet|Furlong/Furlongs|Gill/Gills|Grain/Grains|Hectare/Hectares|"
         "Hertz|Inch/Inches|Kiloampere/Kiloamperes|Kilohertz|Pair/Pairs|Kiloohm/Kiloohms|Kilovolt/Kilovolts|Kilowatt/Kilowatts|Megahertz|"
         "Mile/Miles|Milliampere/Milliamperes|Millihertz|Milliliter/Milliliters|Millimeter/Millimeters|Milliohm/Milliohms|Ounce/Ounces|"
         "Millivolt/Millivolts|Milliwatt/Milliwatts|Nautical Mile/Nautical Miles|Ohm/Ohms|Parcel/Parcels|Perch/Perches|Pint/Pints|Pole/Poles|"
         "Quart/Quarts|Quarter/Quarters|Metric Ton/Metric Tons|Rod/Rods|Roll/Rolls|Square Centimeter/Square Centimeters|Square Foot/Square Feet|"
         "Square Inch/Square Inches|Square Mile/Square Miles|Square Yard/Square Yards|Stone/Stones|Tonne/Tonnes|Tray/Trays|Meter/Meters|"
         "Volt/Volts|Watt/Watts|Wp|Twenty-Foot Container|Strand/Strands|Plant/Plants|Pallet/Pallets|Gross|Forty-Foot Container |Sheet/Sheets|"
         "Long Ton/Long Tons|Carat/Carats|Blade/Blades|Combo/Combos").split("|")
UNIT_NAMES = {u.split("/")[0].lower(): u for u in UNITS}
assert len(HEADERS) == 57 and len(INSTRUCTIONS) == 57, (len(HEADERS), len(INSTRUCTIONS))


def unit_cell(u):
    u = (u or "Piece").strip()
    return u if u in UNITS else UNIT_NAMES.get(u.lower().rstrip("s"), "Piece/Pieces")


def attr(v):
    return re.sub(r"\s+", " ", str(v)).strip()[:49]


def rows_for(pid, l, urls, studio):
    cfg = studio["marketplaces"].get("alibaba", {})
    x = {**cfg.get("xlsx", {}), **l.get("xlsx", {})}
    base = [""] * 57
    base[0] = l["title"]
    for i, u in enumerate(urls[:6]): base[1 + i] = u
    base[7] = l["description_html"]
    base[8] = l.get("place_of_origin") or cfg.get("place_of_origin", "")
    base[9] = l.get("brand_name") or studio["brand"].get("name", "")
    base[10] = l.get("category", "")
    for i, a in enumerate(l.get("attributes", [])[:5]):
        base[11 + 2 * i], base[12 + 2 * i] = attr(a["name"]), attr(a["value"])
    base[21] = "unit"
    base[23] = unit_cell(l.get("unit") or cfg.get("unit"))
    base[24] = (l.get("currency") or cfg.get("currency") or "USD").upper()
    base[27] = l.get("model_number", "")
    if x.get("gross_weight_kg"): base[46] = float(x["gross_weight_kg"])
    if x.get("shipping_template"): base[47] = x["shipping_template"]
    for i, s in enumerate(x.get("lead_times", [])[:3]):
        base[48 + 2 * i], base[49 + 2 * i] = int(s["qty"]), int(s["days"])
    for i, v in enumerate((x.get("dimensions_cm") or [])[:3]): base[54 + i] = float(v)
    skus = l.get("skus", [])
    if skus:
        out = []
        for k, s in enumerate(skus):
            r = list(base)
            r[25] = "SKU pricing"
            r[28] = s.get("code") or f"{l.get('model_number') or pid}-{k + 1:02d}"
            r[29] = float(s["price"])
            for i, (n, v) in enumerate(list(s["attributes"].items())[:4]):
                r[30 + 2 * i], r[31 + 2 * i] = n[:40], str(v)[:70]
            out.append(r)
        if not l.get("model_number"): sys.exit(f"{pid}: SKU rows need model_number (the SPU ID that groups them).")
        return out
    tiers = l.get("price_tiers", [])
    if tiers:
        base[25] = "Tiered pricing"
        for i, t in enumerate(tiers[:3]): base[38 + 2 * i], base[39 + 2 * i] = float(t["price"]), int(t["min_qty"])
    else:
        base[25] = "Range pricing"
        base[44], base[45] = float(l["price_range"]["min"]), float(l["price_range"]["max"])
    return [base]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", required=True)
    ap.add_argument("--only", nargs="*")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    D = os.path.abspath(a.dir)
    studio = load(os.path.join(D, "studio.json"))
    st = load(os.path.join(D, "state.json"), {})
    pub = load(os.path.join(D, "published.json"), {})
    assets = pub.get("assets", {})
    data, problems = [], []
    for key in sorted(st.get("listings", {})):
        pid, m = key.rsplit(".", 1)
        if m != "alibaba" or (a.only and pid not in a.only): continue
        l = load(os.path.join(D, "listings", f"{pid}.alibaba.json"))
        man = load(os.path.join(D, "export", pid, "alibaba", "manifest.json"), [])
        urls = [assets.get(x["sha256"], {}).get("url") for x in man]
        if not man or not all(urls):
            problems.append(f"{pid}: images are not hosted yet (node publish.mjs --dir {a.dir} --upload-only)"); continue
        data += rows_for(pid, l, urls, studio)
    if problems: sys.exit("\n".join(problems))
    if not data: sys.exit("no approved Alibaba listings (listing.py --approve)")
    wb = Workbook(); ws = wb.active; ws.title = "Alibaba default template"
    ws.append([""] * 57)
    ws.append([SECTION.get(i + 1, "") for i in range(57)])
    ws.append(HEADERS)
    ws.append(INSTRUCTIONS)
    for r in data: ws.append(r)
    for c in ws[3]: c.font = Font(bold=True)
    for c in ws[4]: c.alignment = Alignment(wrap_text=True, vertical="top")
    for i, h in enumerate(HEADERS, 1):
        ws.column_dimensions[ws.cell(3, i).column_letter].width = 60 if "description" in h else 48 if "title" in h else 38 if "image" in h else 22
    us = wb.create_sheet("unitSheet")
    for u in UNITS: us.append(["", u])
    out = a.out or os.path.join(D, "export", "alibaba-bulk-upload.xlsx")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    wb.save(out)
    print(f"{len(data)} rows -> {out}\nUpload it in Alibaba seller centre: Products > Manage products > Bulk upload (use the Default template).")


if __name__ == "__main__":
    main()
